### ISSUE TITLE
Things to checkout today

### ISSUE THREAD

**Issue by rschmidt9** [TechKinect/Genius#12]
http://www.ted.com/talks/ethan_nadelmann_why_we_need_to_end_the_war_on_drugs

**Comment by rschmidt9** [comment]
http://techcrunch.com/2014/11/12/microsoft-makes-visual-studio-free-for-small-teams/?ncid=rss&cps=gravity

---

http://www.visualstudio.com/products/how-to-buy-vs

**Comment by rschmidt9** [comment]
http://reesenews.org/2012/03/22/an-incubator-for-innovation/37275/
@TechKinect/owners 
Journalism Incubator on campus. Should we apply?

**Comment by ericpaulsen** [comment]
Yes. However, I couldn't find the application on that website. I'll take on this project and work on the application when I find it.

**Comment by rschmidt9** [comment]
Awesome, I haven't read the article yet and am not sure how it actually works with applying or what they do. Let's talk about this more this evening.

**Comment by rdixonferrell** [comment]
I know some people who are on this, which may give us a foot in the door. However, based off what they've said, Reese primarily comes up with the ideas themselves. Worth looking into though.

**Comment by rschmidt9** [comment]
http://www.ted.com/talks/rodrigo_canales_the_deadly_genius_of_drug_cartels
