### ISSUE TITLE
Creat About Us or Mission page

### ISSUE THREAD

**Issue by rschmidt9** [TechKinect/Genius#13]
@TechKinect/owners 
Hey guys let's do this tomorrow when we meet. Tomorrow being 11/13/14

**Comment by rdixonferrell** [comment]
Here's a good start: 

TechKinect is a curated news platform of the best business, technology and leadership information from best sources all over the web. The site is for young professionals, aged 18 to 30, who are trying to expand their knowledge in these fields, but do not have time to sift through articles on several websites each day. We do that for them. Our content is not limited to articles, but features videos and podcasts, too. Users are encouraged to engage in TechKinect by becoming a contributor and posting content they find helpful and interesting, or engaging in discussion on the site. We hope to inspire users to seek both personal and professional development. Information users choose to engage with on our site will help them both inside and outside of the office. TechKinect will spark your genius.

**Comment by rschmidt9** [comment]
Is this from the application? There's some syntax awkwardness/errors in the first sentence.

**Comment by ericpaulsen** [comment]
Revised (let me know what you think):

TechKinect is a curated news platform delivering you the best business, technology and leadership information from across the web. Our site is for those seeking to expand their knowledge in these fields, but do not have the time to sift through several websites on a daily basis. We do that for you. Our content is not only limited to articles, but features videos and podcasts as well. We encourage you to engage with us by becoming a contributor and posting content you find helpful and interesting, or joining in discussion with fellow users. We hope to inspire you to seek personal and professional development. Information you choose to engage with on our site will both aid you inside and outside of the office. TechKinect will spark your genius.

**Comment by rdixonferrell** [comment]
Done
