### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by rschmidt9** [TechKinect/Genius#15]
In order to streamline the process and avoid confusion I'll handle on-boarding contributors. Most of them we won't give actially access to the site.
@techkinect/owners

**Comment by rschmidt9** [comment]
Why'd you close this?
@ericpaulsen

**Comment by ericpaulsen** [comment]
Didn't think it needed to be open. My bad.

**Comment by rschmidt9** [comment]
It's okay, you just closed it two minutes after I posted it haha

**Comment by rschmidt9** [comment]
@TechKinect/owners
