### ISSUE TITLE
Subscription Emails 

### ISSUE THREAD

**Issue by rdixonferrell** [TechKinect/Genius#17]
Some feedback my dad gave me about the emails.
1. Content is long and a lot to digest at once. We could have less articles in the email, or only put our blurbs.
2. Include the pictures that are with the posts on the site/social media
3.  Have our logo at the top, rather than just our name. Emails from other media outlets do this. We need our brand in our users face at every opportunity. 

@TechKinect/owners

**Comment by rschmidt9** [comment]
Moved to ongoing because we don't have the means to change this right now. However, @akueffner should be looking into how we could make feedburner work better with what we currently have.

**Comment by rschmidt9** [comment]
#24
