### ISSUE TITLE
Business Card Personal Information

### ISSUE THREAD

**Issue by rdixonferrell** [TechKinect/Genius#18]
Making Business Cards for each of us. Post what you would like to appear on the card for the following: Name, Phone #, Email address, Position in TechKinect

@TechKinect/owners

**Comment by ericpaulsen** [comment]
Eric Paulsen
(305) 781-1509
eric.paulsen9@gmail.com
Developer

**Comment by rschmidt9** [comment]
Robert Schmidt
(980) 322-9260
rob@ordercarolina.com
President

**Comment by NoWarmUp** [comment]
Austin Kueffner
(336) 391-7005
austin@ordercarolina.com
Vice-President
