### ISSUE TITLE
Fix the website alignment/layout

### ISSUE THREAD

**Issue by rschmidt9** [TechKinect/Genius#22]
Let us know if you have any questions

**Comment by rschmidt9** [comment]
What's up with this?

**Comment by rdixonferrell** [comment]
The padding between the sidebars and the main body of text in the middle effects the alignment of the "read" and "business. technology. leadership." Does it look better now? I had to lessen the padding between the main body of text and sidebars to center it. 

The only way to get the sidebar buttons on the left size is to add characters. It gets the job done, but does this look cheesy?

"read/watch/listen/about" is weirdly attached to the techkinect logo on the top left. It used to be in the center though so I do not understand this.
