### ISSUE TITLE
Figure out Mail Chimp

### ISSUE THREAD

**Issue by rschmidt9** [TechKinect/Genius#24]
Let's see about getting this up soon!

**Comment by rschmidt9** [comment]
#17

**Comment by ericpaulsen** [comment]
The new TechKinect Newsletter

![screen shot 2014-12-02 at 1 40 35 am](https://cloud.githubusercontent.com/assets/9683576/5258813/70fb259a-79c4-11e4-9ca9-2b106a738b14.png)
