### ISSUE TITLE
Flyer Goals 

### ISSUE THREAD

**Issue by rdixonferrell** [TechKinect/Genius#7]
Comment upon completion of each step:
1. Get approval stamp 
2. Print (x) copies 
3. Post in J-School
4. Post in B-School
5. Post elsewhere? Ideas? 

@schmidtyunc @akueffner @ericpaulsen 

![tkflyer1](https://cloud.githubusercontent.com/assets/9685833/5003438/5f4e90d2-69db-11e4-9342-d33ab6112a42.png)

**Comment by rdixonferrell** [comment]
USE THIS FLYER. IT LOOKS BETTER. 
![tkflyer2](https://cloud.githubusercontent.com/assets/9685833/5003498/5474aa10-69dc-11e4-88cd-08663739deee.png)

**Comment by rdixonferrell** [comment]
@schmidtyunc

**Comment by ericpaulsen** [comment]
Post in Peabody, Carroll and Hanes
