### ISSUE TITLE
Thoughts on #SparkYourGenius

### ISSUE THREAD

**Issue by rschmidt9** [TechKinect/Genius#9]
@TechKinect/owners 

What do you guys think about putting that hashtag on all of our twitter posts?

**Comment by ericpaulsen** [comment]
I think its a great idea. Its another way to get our social media marketing campaign out there. And its something that is exclusive to TechKinect.

**Comment by rdixonferrell** [comment]
I like the idea, but for every single post? Let's look into other media agencies and their hashtag tendencies. We don't want to fatigue users by pushing our brand/slogan too hard. However, if other successful accounts are doing it, let's go for it.

**Comment by rschmidt9** [comment]
Agreed, let's "hash" it out tonight.

**Comment by rschmidt9** [comment]
Let's use this for articles that make you think
